### ISSUE TITLE
时区不生效，挂载目录会无法启动，以及自己构建镜像的一点疑问

### ISSUE THREAD

**Issue by gitiray** [hongyonghan/Docker_Microsoft365_E5_Renew_X#14]
x86_64 架构 Linux VPS

# 时区问题
我看Dockerfile是有设置的，我甚至在 docker run 的时候还重新指定了一次，但网页还是慢8小时，进容器内查看时区还是 UTC

# 挂载问题
初始化时如果用 -v 挂载目录，会出现无法启动的情况
若挂载的目录是 /app，日志
```
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

如果挂载的目录是 /app/Deploy，日志
```
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at ̀̀̀ 
̀̀̀̀̔̍.̀̀̀ 
̀̀̀̀̄̕(Object , ̀̀̀ 
̀̀̀̀̔̍ )
   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
   at Microsoft365_E5_Renew_X.Program.Main(String[] args)
```

对于 /app/Deploy，提前创建好Config.xml可以暂时解决，但教程里并没有提到。
另外我之前使用其它Docker项目时，一般遇到这种情况，容器是会自动生成配置文件的，所以在这里也提一句。

# 自己构建
直接 git clone 本仓库，构建之后运行会报错
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-Microsoft365_E5_Renew_X.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
不知是否和构建过程中的这个提示有关
```
Step 10/11 : RUN dotnet dev-certs https
 ---> Running in 7a6d76f3398e
A valid HTTPS certificate with a key accessible across security partitions was not found. The following command will run to fix it:
'sudo security set-key-partition-list -D localhost -S unsigned:,teamid:UBF8T346G9'
This command will make the certificate key accessible across security partitions and might prompt you for your password. For more information see: https://aka.ms/aspnetcore/2.1/troubleshootcertissues
A valid HTTPS certificate with a key accessible across security partitions was not found. The following command will run to fix it:
'sudo security set-key-partition-list -D localhost -S unsigned:,teamid:UBF8T346G9'
This command will make the certificate key accessible across security partitions and might prompt you for your password. For more information see: https://aka.ms/aspnetcore/3.1/troubleshootcertissues
The HTTPS developer certificate was generated successfully.
Removing intermediate container 7a6d76f3398e
```
另外这样构建出来的镜像应该是完整版，不知道如何构建 slim版

**Comment by hongyonghan** [comment]
1. 时区问题可以看我最新版的部署说明的命令。加入参数-e TZ=Asia/Shanghai。
2. 挂载问题。如果你本地没有Config.xml文件等任何文件，就不能使用-v指令。报错的原因是因为没有这个文件。挂载的目录是 /app/Deploy。可以直接使用命令，会有一个默认的Config.xml文件，然后进入该文件修改密码即可。
3. 自己构建问题。我已经将slim版本的文件上传到github仓库中，可以尝试自己构建。
