### ISSUE TITLE
启动后停留在登录界面，无法添加运行账户

### ISSUE THREAD

**Issue by MuMu-HuaHua** [hongyonghan/Docker_Microsoft365_E5_Renew_X#29]
docker log
```
e5renewx    | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
e5renewx    |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
e5renewx    | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
e5renewx    |       No XML encryptor configured. Key {bb0335e0-8dcf-4932-8679-6ef82f93564d} may be persisted to storage in unencrypted form.
e5renewx    | info: Microsoft.Hosting.Lifetime[0]
e5renewx    |       Now listening on: http://[::]:1066
e5renewx    | info: Microsoft.Hosting.Lifetime[0]
e5renewx    |       Application started. Press Ctrl+C to shut down.
e5renewx    | info: Microsoft.Hosting.Lifetime[0]
e5renewx    |       Hosting environment: Production
e5renewx    | info: Microsoft.Hosting.Lifetime[0]
e5renewx    |       Content root path: /app
e5renewx    | fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
e5renewx    |       An exception was thrown while deserializing the token.
e5renewx    | Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
e5renewx    |  ---> System.Security.Cryptography.CryptographicException: The key {ab8c41d2-3f7f-464b-9872-c8940fa93756} was not found in the key ring.
e5renewx    |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
e5renewx    |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
e5renewx    |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
e5renewx    |    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
e5renewx    |    --- End of inner exception stack trace ---
e5renewx    |    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
e5renewx    |    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```
账户设置、系统设置均为以下界面（输入密码后仍为该界面）
![image](https://user-images.githubusercontent.com/76593526/215713051-6f6eb94a-82bb-4815-94e4-d05084719064.png)

下载源码后挂载到`/app`仍然报错，请问有什么解决办法吗

**Comment by hongyonghan** [comment]
直接拉取镜像运行，容器状态正常吗？
