### ISSUE TITLE
群晖docker安装无法启动

### ISSUE THREAD

**Issue by FrankleeM** [hongyonghan/Docker_Microsoft365_E5_Renew_X#34]
如题
设置截图如下：
![image](https://user-images.githubusercontent.com/32917028/218295724-032b6b3f-c660-428e-afba-191eb9e0e547.png)
环境配置部分未调整，使用默认
![image](https://user-images.githubusercontent.com/32917028/218295752-de237502-69ef-46bd-99fb-858a20f1ed06.png)

日志如下：

2023-02-12 05:23:40	stdout	   at Microsoft365_E5_Renew_X.Program.Main(String[] args)
2023-02-12 05:23:40	stdout	   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
2023-02-12 05:23:40	stdout	 )
2023-02-12 05:23:40	stdout	(Object , ̀̀̀
2023-02-12 05:23:40	stdout	.̀̀̀
2023-02-12 05:23:40	stdout	   at ̀̀̀
2023-02-12 05:23:40	stdout	   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2023-02-12 05:23:40	stdout	   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2023-02-12 05:23:40	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
2023-02-12 05:23:40	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
2023-02-12 05:23:40	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
2023-02-12 05:23:40	stdout	Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.
2023-02-12 05:23:34	stdout	   at Microsoft365_E5_Renew_X.Program.Main(String[] args)
2023-02-12 05:23:34	stdout	   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
2023-02-12 05:23:34	stdout	 )
2023-02-12 05:23:34	stdout	(Object , ̀̀̀
2023-02-12 05:23:34	stdout	.̀̀̀
2023-02-12 05:23:34	stdout	   at ̀̀̀
2023-02-12 05:23:34	stdout	   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2023-02-12 05:23:34	stdout	   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2023-02-12 05:23:34	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
2023-02-12 05:23:34	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
2023-02-12 05:23:34	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
2023-02-12 05:23:34	stdout	Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.
2023-02-12 05:23:30	stdout	   at Microsoft365_E5_Renew_X.Program.Main(String[] args)
2023-02-12 05:23:30	stdout	   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
2023-02-12 05:23:30	stdout	 )
2023-02-12 05:23:30	stdout	(Object , ̀̀̀
2023-02-12 05:23:30	stdout	.̀̀̀
2023-02-12 05:23:30	stdout	   at ̀̀̀
2023-02-12 05:23:30	stdout	   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2023-02-12 05:23:30	stdout	   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2023-02-12 05:23:30	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
2023-02-12 05:23:30	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
2023-02-12 05:23:30	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
2023-02-12 05:23:30	stdout	Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.
2023-02-12 05:23:27	stdout	   at Microsoft365_E5_Renew_X.Program.Main(String[] args)
2023-02-12 05:23:27	stdout	   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
2023-02-12 05:23:27	stdout	 )
2023-02-12 05:23:27	stdout	(Object , ̀̀̀
2023-02-12 05:23:27	stdout	.̀̀̀
2023-02-12 05:23:27	stdout	   at ̀̀̀
2023-02-12 05:23:27	stdout	   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2023-02-12 05:23:27	stdout	   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2023-02-12 05:23:27	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
2023-02-12 05:23:27	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
2023-02-12 05:23:27	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
2023-02-12 05:23:27	stdout	Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.
2023-02-12 05:23:24	stdout	   at Microsoft365_E5_Renew_X.Program.Main(String[] args)
2023-02-12 05:23:24	stdout	   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
2023-02-12 05:23:24	stdout	 )
2023-02-12 05:23:24	stdout	(Object , ̀̀̀
2023-02-12 05:23:24	stdout	.̀̀̀
2023-02-12 05:23:24	stdout	   at ̀̀̀
2023-02-12 05:23:24	stdout	   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2023-02-12 05:23:24	stdout	   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2023-02-12 05:23:24	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
2023-02-12 05:23:24	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
2023-02-12 05:23:24	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
2023-02-12 05:23:24	stdout	Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.
2023-02-12 05:23:20	stdout	   at Microsoft365_E5_Renew_X.Program.Main(String[] args)
2023-02-12 05:23:20	stdout	   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
2023-02-12 05:23:20	stdout	 )
2023-02-12 05:23:20	stdout	(Object , ̀̀̀
2023-02-12 05:23:20	stdout	.̀̀̀
2023-02-12 05:23:20	stdout	   at ̀̀̀
2023-02-12 05:23:20	stdout	   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2023-02-12 05:23:20	stdout	   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2023-02-12 05:23:20	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
2023-02-12 05:23:20	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
2023-02-12 05:23:20	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
2023-02-12 05:23:20	stdout	Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.
2023-02-12 05:23:15	stdout	   at Microsoft365_E5_Renew_X.Program.Main(String[] args)
2023-02-12 05:23:15	stdout	   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
2023-02-12 05:23:15	stdout	 )
2023-02-12 05:23:15	stdout	(Object , ̀̀̀
2023-02-12 05:23:15	stdout	.̀̀̀
2023-02-12 05:23:15	stdout	   at ̀̀̀
2023-02-12 05:23:15	stdout	   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2023-02-12 05:23:15	stdout	   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2023-02-12 05:23:15	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
2023-02-12 05:23:15	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
2023-02-12 05:23:15	stdout	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
2023-02-12 05:23:15	stdout	Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.

**Comment by FrankleeM** [comment]
从首页下载了配置文件上传到自建目录后已经解决

**Comment by hongyonghan** [comment]
因为容器里面都有的，不需要设置到/Deploy路径，如果想要备份的话，直接设置到/app路径即可

**Comment by mayziran** [comment]
> 因为容器里面都有的，不需要设置到/Deploy路径，如果想要备份的话，直接设置到/app路径即可

群晖挂载/app应该是因为没有权限，能让容器内程序以root用户运行吗，添加个修改uid gid的环境变量
