### ISSUE TITLE
docker启动失败

### ISSUE THREAD

**Issue by nooneandU** [hongyonghan/Docker_Microsoft365_E5_Renew_X#35]
CentOS8

Unhandled exception. System.IO.FileNotFoundException: The configuration file 'Config.xml' was not found and is not optional. The physical path is '/app/Deploy/Config.xml'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at ̀̀̀
̀.̀̀̀
̀(Object , ̀̀̀
̀ )
   at Microsoft365_E5_Renew_X.Core.SystemConfig.Static.LoadXMLConfig(String XMLFilePath)
   at Microsoft365_E5_Renew_X.Program.Main(String[] args)

**Comment by hongyonghan** [comment]
考虑直接拉取镜像运行，不配置数据卷呢？
